export const locales = ["es", "en"] as const;

export type Locale = (typeof locales)[number];

export type Dictionary = {
  hero: {
    kicker: string;
    title: string;
    body: string;
  };
  common: {
    save: string;
    saving: string;
    send: string;
    sending: string;
    back: string;
    continueLabel: string;
    close: string;
    skipForNow: string;
  };
  header: {
    brandTagline: string;
    brandAriaLabel: string;
    navAriaLabel: string;
    mobileNavAriaLabel: string;
    vpdAriaLabel: string;
    vpdShort: string;
    vpdLong: string;
    installButton: string;
    installHintMobile: string;
    installAccepted: string;
    installDismissed: string;
    demoBadge: string;
    themeToLight: string;
    themeToDark: string;
  };
  sharedView: {
    readOnly: string;
    viewingMessage: string;
    show: string;
    hide: string;
    myGrows: string;
  };
  account: {
    avatarSignedInLabel: string;
    avatarSignedOutLabel: string;
    closeAriaLabel: string;
    dialogEyebrow: string;
    dialogTitleSignedIn: string;
    dialogTitleSignedOut: string;
    signedInIntro: string;
    signOut: string;
    shareTitle: string;
    shareHint: string;
    generateCode: string;
    viewOthersTitle: string;
    codeInputAriaLabel: string;
    codePlaceholder: string;
    useCode: string;
    viewGrowsOf: string;
    signedOutIntro: string;
    emailLabel: string;
    emailPlaceholder: string;
    sendLink: string;
    privacyLink: string;
    connectedPill: string;
    signInPill: string;
    localDemoPill: string;
    savedByUserPill: string;
    savedByUserPillHome: string;
    homeTitle: string;
    homeIntro: string;
    saveNow: string;
    emailAriaLabel: string;
    defaultInfoMessage: string;
    demoInfoMessage: string;
  };
  onboarding: {
    eyebrow: string;
    skip: string;
    back: string;
    continueLabel: string;
    goToToday: string;
    steps: Array<{ title: string; body: string }>;
  };
  stepper: {
    ariaLabel: string;
    previous: string;
    next: string;
    start: string;
    backToToday: string;
    today: string;
  };
  push: {
    eyebrow: string;
    title: string;
    signInPrompt: string;
    unsupported: string;
    description: string;
    activate: string;
    deactivate: string;
    saving: string;
    deactivatedMessage: string;
    activatedMessage: string;
    deniedMessage: string;
    failedMessage: string;
    errorMessage: string;
  };
  today: {
    panelEyebrow: string;
    heroTitle: string;
    statsGrowsLabel: string;
    statsGrowsDescription: string;
    statsPendingLabel: string;
    statsPendingDescription: string;
    statsStreakLabel: string;
    statsStreakDescription: string;
    statsStreakValue: string;
    tasksEyebrow: string;
    tasksTitle: string;
    tasksEmptyTitle: string;
    tasksEmptyBody: string;
    taskDone: string;
    taskPending: string;
    taskPriority: string;
    weatherEyebrow: string;
    weatherTitle: string;
    weatherLive: string;
    weatherPending: string;
    weatherRefresh: string;
    weatherUseDevice: string;
    growCommandEyebrow: string;
    growCommandTitle: string;
    growCommandBody: string;
    growCommandStagesAriaLabel: string;
    growCommandStageSeed: string;
    growCommandStageVeg: string;
    growCommandStageFlower: string;
    growCommandStageHarvest: string;
    growCommandActivePlants: string;
    growCommandNoPlants: string;
    growCommandUpcomingEvents: string;
    growCommandNoEvents: string;
    accountConnectedPill: string;
    accountSignInPill: string;
    accountLocalDemoPill: string;
    accountSavedByUserPill: string;
    coachEyebrow: string;
    coachTitle: string;
    coachManualPill: string;
    coachIntro: string;
    coachFocusLabel: string;
    coachFocusFallback: string;
    coachPlantFallback: string;
    coachSignalLeavesLabel: string;
    coachSignalLeavesHint: string;
    coachSignalSubstrateLabel: string;
    coachSignalSubstrateHint: string;
    coachSignalPestsLabel: string;
    coachSignalPestsHint: string;
    coachSignalLightLabel: string;
    coachSignalLightHint: string;
    coachSignalPhotoLabel: string;
    coachSignalPhotoHint: string;
    coachCheckedMark: string;
    seasonEyebrow: string;
    seasonTitle: string;
    seasonTasksDonePercent: string;
    seasonDaysSinceStart: string;
    seasonNextMilestoneLabel: string;
    seasonNextMilestoneValue: string;
    seasonNextMilestoneEmpty: string;
    seasonPlantFallback: string;
    stageSummaryEyebrow: string;
    stageSummaryTitle: string;
    stageSummaryDaysSince: string;
    stageSummaryNoDate: string;
    stageSummaryFooter: string;
    inventoryAlertsEyebrow: string;
    inventoryAlertsTitle: string;
    inventoryAlertsQuantity: string;
    inventoryAlertsExpiredOn: string;
    inventoryAlertsExpiresOn: string;
    inventoryAlertsRemoveMinimum: string;
    inventoryAlertsFooter: string;
    inspectionsEyebrow: string;
    inspectionsTitle: string;
    inspectionsPotFallback: string;
    inspectionsPendingReview: string;
    inspectionsNextReview: string;
    inspectionsViewPlant: string;
    environmentAlertsEyebrow: string;
    environmentAlertsTitle: string;
    environmentAlertsBody: string;
    environmentAlertsActive: string;
    environmentAlertsNoneActive: string;
    environmentAlertsBelowMin: string;
    environmentAlertsAboveMax: string;
    environmentAlertsLastReading: string;
    environmentAlertsAcknowledge: string;
    environmentAlertsViewPlant: string;
    environmentAlertsEmptyConfigured: string;
    environmentAlertsEmptyUnconfigured: string;
    environmentAlertsFooter: string;
    quickAccessEyebrow: string;
    quickAccessTitle: string;
    quickAccessBody: string;
    quickAccessPending: string;
    quickAccessAllUpToDate: string;
    quickAccessRegister: string;
    quickAccessLastMeasurement: string;
    quickAccessNoMeasurements: string;
    toolboxMeasurementLabel: string;
    toolboxTasksLabel: string;
    toolboxWeatherLabel: string;
    headerTasksToday: string;
    headerNoTasksToday: string;
    attentionEyebrow: string;
    attentionTitle: string;
    attentionCountPill: string;
    attentionAllClearTitle: string;
    attentionAllClearBody: string;
    attentionChipMeasurement: string;
    attentionChipInspection: string;
    attentionChipInventory: string;
    plantsEyebrow: string;
    plantsDay: string;
    plantsNoVariety: string;
  };
  seeds: {
    eyebrow: string;
    title: string;
    legalRulePill: string;
    legalBannerText: string;
    reprocannQuestion: string;
    reprocannLink: string;
    tabsAriaLabel: string;
    tabFinder: string;
    tabManual: string;
    tabHorticultural: string;
    tabSetups: string;
    tabReference: string;
    manualEyebrow: string;
    manualTitle: string;
    selectedFromFinder: string;
    stepperAriaLabel: string;
    stepperPrevious: string;
    stepperStart: string;
    stepperNext: string;
    stepperEnd: string;
    modeAutomatic: string;
    modeManual: string;
    copyFieldPrefix: string;
    targetFloweringWeeks: string;
    targetDaysToFlower: string;
    targetPotLiters: string;
    targetLightType: string;
    targetDeclaredType: string;
    targetGeneticNote: string;
    targetReferenceNote: string;
    targetSourceNote: string;
    targetManualWateringNote: string;
    targetManualNote: string;
    notDeclared: string;
    weeksUnit: string;
    geneticTypeAutoflowering: string;
    geneticTypeFasterFlowering: string;
    geneticTypeRegular: string;
    geneticTypeFeminized: string;
    setups: {
      eyebrow: string;
      title: string;
      introText: string;
      sectorLabel: string;
      spaceTypes: Array<{ id: string; label: string }>;
      tentSizeLabel: string;
      greenhouseTypeLabel: string;
      outdoorPlaceLabel: string;
      outdoorPlaces: string[];
      greenhousePlaces: string[];
      referenceGeneticLabel: string;
      noGeneticSelected: string;
      selectedSetupLabel: string;
      outdoorBestFor: string;
      presets: Array<{
        id: string;
        label: string;
        comfortable: string;
        compact: string;
        airflow: string;
        lightFit: string;
        plantHeight: string;
        bestFor: string;
      }>;
      comfortableLabel: string;
      comfortableNote: string;
      outdoorComfortableValue: string;
      compactLabel: string;
      compactNote: string;
      outdoorCompactValue: string;
      airflowLabel: string;
      airflowNote: string;
      outdoorAirflowValue: string;
      lightFitLabel: string;
      lightFitNote: string;
      outdoorLightValue: string;
      heightLabel: string;
      heightNote: string;
      outdoorHeightValue: string;
      selectedGeneticLabel: string;
      noGeneticLabel: string;
      geneticTypeLabel: string;
      floweringPublishedLabel: string;
      thcPublishedLabel: string;
      sourceLabel: string;
      pickGeneticHint: string;
      checklistLabel: string;
      tasks: Array<{ title: string; cadence: string; detail: string }>;
      manualTaskFieldLabel: string;
      quickRuleLabel: string;
      potSmallLabel: string;
      potSmallValue: string;
      potMediumLabel: string;
      potMediumValue: string;
      potLargeLabel: string;
      potLargeValue: string;
    };
    reference: {
      readOnly: string;
      title: string;
      geneticsLoadedCount: string;
      regulatedTypesLabel: string;
      fieldType: string;
      fieldVariant: string;
      fieldNote: string;
      chooseGeneticLabel: string;
      noGeneticSelected: string;
      alphabeticalListHint: string;
      searchGeneticLabel: string;
      byTypeSummary: string;
      geneticsSheetSummary: string;
      chooseGeneticHint: string;
      fieldSource: string;
      fieldCross: string;
      floweringPublished: string;
      thcPublished: string;
      fieldFlavor: string;
      fieldEffect: string;
      rawFieldsSummary: string;
      fieldDaysToFlower: string;
      fieldFlowering: string;
      fieldPot: string;
      fieldLight: string;
      fieldWatering: string;
    };
    finder: {
      eyebrow: string;
      title: string;
      description: string;
      modeLabel: string;
      educationSummary: string;
      thcTitle: string;
      thcBody: string;
      floweringTitle: string;
      floweringBody: string;
      seedTypeTitle: string;
      seedTypeBody: string;
      stepCountTemplate: string;
      placeOptions: Array<{ id: string; icon: string; label: string; description: string }>;
      seedTypeOptions: Array<{ id: string; icon: string; label: string; description: string }>;
      potencyOptions: Array<{ id: string; icon: string; label: string; description: string }>;
      flavorOptions: Array<{ id: string; icon: string; label: string; description: string }>;
      flavorsStepTitle: string;
      flavorsStepHint: string;
      resultsTitle: string;
      resultsHint: string;
      matchSummaryNoFilters: string;
      matchSummaryTemplate: string;
      emptyResultsMessage: string;
      addSeedButton: string;
      showMoreButtonTemplate: string;
      backButton: string;
      continueFiltersButton: string;
      startOverButton: string;
      sourceLabel: string;
      thcNotDeclared: string;
      noNotesMessage: string;
    };
    manualForm: {
      groupIdentification: string;
      groupCultivationData: string;
      groupDatesReminders: string;
      searchGeneticLabel: string;
      searchGeneticPlaceholder: string;
      searchGeneticAriaLabel: string;
      suggestionsAriaLabel: string;
      selectedGeneticLabel: string;
      typeLabel: string;
      floweringLabel: string;
      noGeneticHelp: string;
      geneticsAvailableCountTemplate: string;
      spaceTypeLabel: string;
      spaceTypeOptions: string[];
      indoorSizeLabel: string;
      indoorSizeOptions: string[];
      lightTypeLabel: string;
      lightTypeOptions: string[];
      seedTypeOptions: Array<{ label: string; value: string }>;
      daysToFlowerOptions: string[];
      floweringWeeksOptions: string[];
      potOptions: string[];
      referenceNotAutocompleteLabel: string;
      pickGeneticPlaceholder: string;
      referenceHelpText: string;
      geneticTypeReferenceLabel: string;
      daysToFlowerReferenceLabel: string;
      floweringReferenceLabel: string;
      potReferenceLabel: string;
      thcReferenceLabel: string;
      thcNotePlaceholder: string;
      manualTargetGenericLabel: string;
      suggestedAgendaLabel: string;
      quickManualReviewsLabel: string;
      editableLabel: string;
      presets: Array<{ title: string; summary: string }>;
      presetsNote: string;
      moistureLabel: string;
      stageLabel: string;
      dryingLabel: string;
      maintenanceLabel: string;
      photoLabel: string;
      structureLabel: string;
      nutritionLabel: string;
      pestLabel: string;
      closingLabel: string;
      recurrenceLabel: string;
      recurrenceEndLabel: string;
      reminderOptions: Array<{ label: string; value: string }>;
      recurrenceOptions: Array<{ label: string; value: string }>;
      recurrenceEndOptions: Array<{ label: string; value: string }>;
      createEventsButton: string;
      viewCalendarLink: string;
      noManualDatesMessage: string;
      eventsAddedMessageTemplate: string;
      suggestionAppliedTemplate: string;
      disclaimerText: string;
      pasteButton: string;
      pasteUnsupported: string;
      pasteEmptyClipboard: string;
      pasteFailed: string;
      pastedIntoTemplate: string;
      pastedOptionLabelTemplate: string;
      recentlyUsedLabel: string;
      optionsLabel: string;
      doseUnitAriaLabel: string;
      eventMoistureTitle: string;
      eventMoistureDescription: string;
      eventStageTitle: string;
      eventStageDescription: string;
      eventDryingTitle: string;
      eventDryingDescription: string;
      eventMaintenanceTitle: string;
      eventMaintenanceDescription: string;
      eventPhotoTitle: string;
      eventPhotoDescription: string;
      eventStructureTitle: string;
      eventStructureDescription: string;
      eventNutritionTitle: string;
      eventNutritionDescription: string;
      eventPestTitle: string;
      eventPestDescription: string;
      eventClosingTitle: string;
      eventClosingDescription: string;
      eventGeneticSuffixTemplate: string;
      eventTypeSuffixTemplate: string;
    };
    horticultureCalculator: {
      eyebrow: string;
      title: string;
      statusActive: string;
      statusMissing: string;
      seedLabel: string;
      potLabel: string;
      lightLabel: string;
      lightOptions: Array<{ value: string; label: string }>;
      indoorLabel: string;
      indoorOptions: Array<{ value: string; label: string }>;
      resultSeedLabel: string;
      resultSubstrateLabel: string;
      resultWaterCheckLabel: string;
      resultWaterAmountLabel: string;
      resultLightLabel: string;
      resultSpaceLabel: string;
      harvestWindowLabel: string;
      missingPrefix: string;
      dataOriginLabel: string;
      originLabel: string;
      originCatalog: string;
      originCalculated: string;
      originMeasurement: string;
      originSuggestion: string;
      originUser: string;
      originMissing: string;
      seedNotDeclared: string;
      missingHarvestWindow: string;
      missingPotLiters: string;
      missingLightType: string;
      missingIndoorSize: string;
      missingDataLabel: string;
      insufficientDataPrefix: string;
      note: string;
      waterCheckLeafTemplate: string;
      waterCheckPerennialTemplate: string;
      waterCheckDefaultTemplate: string;
      waterCheckExtraSun: string;
      lightFitLeafSun: string;
      lightFitLeafDefault: string;
      lightFitAromaticMixed: string;
      lightFitAromaticDefault: string;
      lightFitDefault: string;
      spaceFitFruitSmall: string;
      spaceFitFruitDefault: string;
      spaceFitPerennial: string;
      spaceFitDefault: string;
    };
    nutrientCalculator: {
      eyebrow: string;
      title: string;
      description: string;
      reservoirLabel: string;
      productLabel: string;
      productPlaceholder: string;
      doseLabel: string;
      doseUnitAriaLabel: string;
      totalForReservoirLabel: string;
      noDataLabel: string;
      removeButton: string;
      addProductButton: string;
      totalMixLabel: string;
      invalidReservoirMessage: string;
      noProductsMessage: string;
      summaryTemplate: string;
    };
  };
  spaces: {
    eyebrow: string;
    title: string;
    description: string;
    searchLabel: string;
    searchAriaLabel: string;
    searchPlaceholder: string;
    newSpaceButton: string;
    cancelButton: string;
    nameLabel: string;
    namePlaceholder: string;
    modeLabel: string;
    modeOutdoor: string;
    modeIndoor: string;
    modeGreenhouse: string;
    regionLabel: string;
    regionPlaceholder: string;
    privacyLabel: string;
    privacyApproxRegion: string;
    privacyPrivateIndoor: string;
    createSpaceButton: string;
    spaceCreatedMessage: string;
    undeclaredRegion: string;
    editSpaceButton: string;
    cancelEditButton: string;
    movePlantsToLabel: string;
    deleteSpaceButton: string;
    cannotDeleteHint: string;
    saveChangesButton: string;
    deleteConfirmWithPlantsTemplate: string;
    deleteConfirmNoPlantsTemplate: string;
    potSingular: string;
    potPlural: string;
    otherSpaceFallback: string;
    measurementCardEyebrow: string;
    measurementCardTitle: string;
    measurementCardBadge: string;
    measurementCardCopy: string;
    measurementCardExpandLabel: string;
    measurementCardCollapseLabel: string;
    plantOrPotLabel: string;
    noPlantsEmptyTitle: string;
    noPlantsEmptyBody: string;
    genReferenceEyebrow: string;
    genReferenceTitle: string;
    genReferenceCopy: string;
    genReferenceGeneticLabel: string;
    genReferenceSelectPlaceholder: string;
    genReferenceQuantityLabel: string;
    viewSheetButton: string;
    declaredPotsAriaLabel: string;
    potLabelTemplate: string;
    sameGeneticNote: string;
    noResultsTitle: string;
    noResultsBody: string;
    measurementForm: {
      dateTimeLabel: string;
      sourceLabel: string;
      sourceManual: string;
      sourceDevice: string;
      temperatureLabel: string;
      humidityLabel: string;
      leafTemperatureLabel: string;
      substrateMoistureLabel: string;
      ppfdLabel: string;
      heightLabel: string;
      irrigationLegend: string;
      irrigationHint: string;
      waterAppliedLabel: string;
      phMeasuredLabel: string;
      ecMeasuredLabel: string;
      ppmMeasuredLabel: string;
      runoffAmountLabel: string;
      runoffPhLabel: string;
      runoffEcLabel: string;
      photoLabel: string;
      photoErrorMessage: string;
      observationsLabel: string;
      vpdLiveLabel: string;
      vpdMissingPrompt: string;
      vpdMissingPrefix: string;
      vpdMissingFallback: string;
      vpdLeafLabel: string;
      vpdAirLabel: string;
      vpdEstimatedTemplate: string;
      vpdFormulaNote: string;
      vpdLeafNote: string;
      vpdNoLeafNote: string;
      saveChangesButton: string;
      saveMeasurementButton: string;
      environmentalStatusInRange: string;
      environmentalStatusLow: string;
      environmentalStatusHigh: string;
      environmentalStatusCritical: string;
      environmentalStatusMissing: string;
    };
  };
};

export type GrowMode = "Exterior" | "Interior" | "Invernadero";

export type DataOrigin = "catalog" | "calculated" | "measurement" | "missing" | "suggestion" | "user";

export type DataConfidence = "high" | "low" | "medium" | "unknown";

export type DataPoint<T = string | number | boolean | null> = {
  capturedAt?: string;
  confidence?: DataConfidence;
  label: string;
  note?: string;
  origin: DataOrigin;
  unit?: string;
  value: T;
};

export type GrowSpace = {
  id: string;
  name: string;
  mode: GrowMode;
  region: string;
  privacyLevel: "Region aproximada" | "Interior privado";
};

export type Plant = {
  id: string;
  spaceId: string;
  name: string;
  variety: string;
  startedAt: string;
  stage: string;
  mode: GrowMode;
  pot: string;
  substrate: string;
  lighting: string;
  photoperiodHours?: number;
  lightsOnTime?: string;
  bank?: string;
  legalRecordStatus?: string;
  setup?: string;
  lifecycle?: "active" | "archived";
  completedAt?: string;
  closingNotes?: string;
  finalWetWeightG?: number;
  finalDryWeightG?: number;
  cycleOutcome?: "completed" | "partial" | "stopped";
  lessonsLearned?: string;
  cyclePlanNotes?: string;
  targetCycleDays?: number;
  targetDryWeightG?: number;
  nextCyclePlan?: string;
};

export type PlantStageTransition = {
  id: string;
  plantId: string;
  fromStage: string;
  toStage: string;
  changedAt: string;
  note?: string;
  source: "user";
};

export type Task = {
  id: string;
  title: string;
  description: string;
  status: "open" | "done";
  frequency: "Manual" | "Diaria" | "Semanal" | "Recurrente";
  category: "Riego" | "Mantenimiento" | "Observacion" | "Registro";
  dueDate?: string;
  plantId?: string;
};

export type CareEntry = {
  id: string;
  plantId?: string;
  title: string;
  createdAt: string;
  note: string;
  photoDataUrl?: string;
  tags: string[];
};

export type PlantMeasurement = {
  id: string;
  plantId: string;
  measuredAt: string;
  source: "device" | "manual" | "sensor";
  temperatureC?: number;
  leafTemperatureC?: number;
  ambientHumidityPercent?: number;
  substrateMoisturePercent?: number;
  heightCm?: number;
  potWeightG?: number;
  waterAmountMl?: number;
  irrigationPh?: number;
  irrigationEcMsCm?: number;
  irrigationPpm?: number;
  runoffAmountMl?: number;
  runoffPh?: number;
  runoffEcMsCm?: number;
  ppfdUmolM2S?: number;
  lighting?: string;
  observations?: string;
  photoDataUrl?: string;
  importBatchId?: string;
  importSource?: string;
};

export type SensorDevice = {
  id: string;
  plantId: string;
  name: string;
  active: boolean;
  lastSeenAt?: string;
  createdAt: string;
};

export type PlantEnvironmentalAlertSettings = {
  plantId: string;
  temperatureMinC?: number;
  temperatureMaxC?: number;
  humidityMinPercent?: number;
  humidityMaxPercent?: number;
  vpdMinKpa?: number;
  vpdMaxKpa?: number;
  substrateMoistureMinPercent?: number;
  substrateMoistureMaxPercent?: number;
  minimumConsecutiveReadings?: number;
  minimumDurationMinutes?: number;
  hysteresisPercent?: number;
};

export type IrrigationRecipe = {
  id: string;
  name: string;
  waterAmountMl?: number;
  irrigationPh?: number;
  irrigationEcMsCm?: number;
  irrigationPpm?: number;
  observations?: string;
  inventoryItemId?: string;
  inventoryAmountPerPlant?: number;
};

export type InventoryItem = {
  id: string;
  name: string;
  category: "nutrient" | "substrate" | "treatment" | "other";
  quantity: number;
  unit: string;
  minimumQuantity?: number;
  notes?: string;
  catalogProductId?: string;
  lotNumber?: string;
  expiresAt?: string;
  sourceUrl?: string;
};

export type InventoryMovement = {
  id: string;
  inventoryItemId: string;
  itemName: string;
  occurredAt: string;
  kind: "initial" | "adjustment" | "consumption";
  quantityDelta: number;
  quantityAfter: number;
  unit: string;
  reason: string;
  plantIds?: string[];
  unitCost?: number;
  totalCost?: number;
  currency?: string;
};

export type InventoryMovementContext = {
  kind?: InventoryMovement["kind"];
  occurredAt?: string;
  reason?: string;
  plantIds?: string[];
};

export type ProductCatalogItem = {
  id: string;
  name: string;
  brand?: string;
  category: InventoryItem["category"];
  composition?: string;
  compatibleStages: string[];
  compatibleModes: GrowMode[];
  packageQuantity?: number;
  packageUnit?: string;
  price?: number;
  currency?: string;
  sourceUrl?: string;
  sourceCheckedAt?: string;
  notes?: string;
};

export type PlantInspection = {
  id: string;
  plantId: string;
  inspectedAt: string;
  category: "pest" | "symptom" | "structure" | "other";
  area: string;
  severity: "low" | "medium" | "high";
  observation: string;
  photoDataUrl?: string;
  followUpDate?: string;
  status: "open" | "resolved";
};

export type PlantAnalysisContext = {
  calendarEvents: CalendarEvent[];
  entries: CareEntry[];
  measurements: PlantMeasurement[];
  missingData: string[];
  plant: Plant;
  tasks: Task[];
  timelineSummary: DataPoint[];
};

export type PlantInsight = {
  id: string;
  createdAt: string;
  plantId: string;
  title: string;
  body: string;
  evidence: DataPoint[];
  kind: "alert" | "comparison" | "missing-data" | "trend";
  source: "calculated" | "suggestion";
};

export type CalendarDay = {
  isoDate: string;
  label: string;
  isToday: boolean;
  isCurrentMonth: boolean;
  items: string[];
};

export type CalendarEventKind = "watering" | "photo" | "cleaning" | "review";

export type CalendarEventRecurrence = {
  active: boolean;
  everyDays: number;
  endDate?: string;
};

export type CalendarEvent = {
  id: string;
  plantId: string;
  title: string;
  description: string;
  kind: CalendarEventKind;
  startDate: string;
  recurrence?: CalendarEventRecurrence;
  completedDates: string[];
  source: "manual" | "horticultural";
};

export type CalendarEventOccurrence = {
  occurrenceId: string;
  eventId: string;
  plantId: string;
  title: string;
  description: string;
  kind: CalendarEventKind;
  date: string;
  completed: boolean;
  source: CalendarEvent["source"];
};
